### ISSUE TITLE
Light Switches

### ISSUE THREAD

**Issue by MACscr** [xillwillx/433Mhz#1] opened 2015-05-20 12:06 UTC
How do you plan to handle manual control of the light bulbs? Are users expected to only use web interfaces/automation to handle turning them off or on? Soon as there is an economical way to control the lights from physical switch, they (wireless bulbs) just dont seem as practical as making the switches themselves wireless.

**Comment by xillwillx** [comment] 2015-05-21 01:21
the bulbs are the same as the plugs they have a remote and can be controlled with 433mhz signals.
the only difference on the bulbs is they don't have a seperate on/off code. its sames the same code for on or off.

**Comment by MACscr** [comment] 2015-05-21 01:28
Remotes are not light switches. Regular light switches have to be on all the time for the bulbs to be wirelessly controlled, thus they are turned into worthless switches.
- Mark

**Comment by jatmn** [comment] 2015-05-21 15:09
This honestly sounds like a pointless argument MARscr. As the intention of the project was to control the wireless bulb sockets and outlets. To achieve what you are talking about you would need to do a physical rewire in house/office in question, removing the power switch at the wall from the loop and directly powering the light socket or replacing the switch with a wireless one. Granted this setup would work as well. Why bother with your needless comments that are not value added at all. Of course hes got no control over a physical power switch at the wall. Normal people who are doing this sorts of thing would either remove the power switch from the loop on there own or just warn everyone not to turn off the switch, that's how we do things where I'm from as with nearly everywhere else.

**Comment by MACscr** [comment] 2015-05-21 15:19
I am not trying to argue. I am trying to problem solve and I havent seen to many people try to tackle it. Unless you are just a hobbyist that lives alone or just with a few roommates versus a spouse, app/web access only typically isn't going to fly when you have to get up in the middle of the night for something or getting home late at night, etc. Might still be cool, but not actually practical.

**Comment by jatmn** [comment] 2015-05-21 15:22
Right, but the point of this project like I said was to control outlet and socket in-line connectors.. Not wireless wall switches.. That is for a different project or if the developer were to choose to include that to the scope of the project.

This is not a bug, I would recommend closing this issue.

**Comment by xillwillx** [comment] 2015-05-21 15:27
this is part of a bigger automation for an uncle in a wheelchair so for him its very practical. it doesnt fit your use then dont use the code and go rewire your house to accommodate

**Closed as completed** 2015-05-21 15:29 UTC
